# resolver: lts-1.10
# resolver: lts-2.0

resolver: lts-6.14 # 0.9.7.0

packages:
- '.'
# - location: '../../websockets'
#   extra-dep: true

allow-newer: true

extra-deps:
# - websockets-0.9.0.0
# - websockets-0.8.2.6
# - atomic-primops-0.8.0.4
# - websockets-0.9.6.1 # version wearewizards.io used, shows same problems

- websockets-0.9.6.2
- unagi-chan-0.4.0.0

# - websockets-0.8.2.6
# - atomic-primops-0.8.0.4
# - io-streams-1.1.4.6

# - attoparsec-0.12.1.6
# - blaze-builder-0.3.3.4
# - io-streams-1.1.4.6
# - network-2.5.0.0
# - random-1.0.1.3
# - text-1.1.1.4

flags: {}

extra-package-dbs: []
